config/routes.rb
Isk::Application.routes.draw do

  root to: "slides#index"

  get "monitor", to: "monitor#index"
  get "/isk_general" => "tubesock#general"

  concern :acl do
    resource :permission, only: [:create, :destroy]
  end

  resources :displays do
    concerns :acl
    resources :history, only: [:index, :show] do
      collection do
        post "clear"
      end
    end

    member do
      get "presentation"
      get "slide_queue"
      post "sort_queue"
      post "remove_override"
      post "clear_queue"
      put "update_override"
      get "dpy_control"
      get "websocket"
      get "dpy"
      get "dpy_local_control"
    end

    collection do
      post "hello"
    end
  end

  resources :events, except: :destroy do
    member do
      post "generate_images"
    end

    collection do
    end
  end

  resources :groups do
    concerns :acl

    member do
      post "sort", as: "sort"
      get "add_slides"
      post "adopt_slides"
      post "hide_all"
      post "publish_all"
      post "add_to_override"
      get "download_slides"
    end
  end

  resource :login do
  end

  resources :presentations do
    concerns :acl

    member do
      post "sort", as: "sort"
      post "add_group"
      post "remove_group"
      get "preview"
      post "add_to_override"
    end

    collection do
    end
  end

  resources :schedules do
    member do
    end

    collection do
    end
  end

  resources :slides do
    concerns :acl
    resources :history, only: [:index, :show] do
      collection do
        post "clear"
      end
    end

    resource :image, only: [:show]

    member do
      get "preview"
      get "full"
      get "svg_data"
      post "svg_data" => :svg_save, as: "svg_save"
      post "ungroup"
      post "undelete"
      post "hide"
      post "to_inkscape"
      post "to_simple"
      post "add_to_group"
      post "add_to_override"
      post "clone"
      get "thumb"
    end

    collection do
    end
  end

  resources :templates do
    member do
      post :sort
    end

    collection do
    end
  end

  resources :tickets do
    member do
    end

    collection do
    end
  end

  resources :users do
    member do
      get "roles"
      post "grant"
    end

    collection do
    end

    resources :tokens, only: [:create, :destroy]
  end
end

app/controllers/history_controller.rb
# frozen_string_literal: true

# ISK - A web controllable slideshow system
#
# Author::		Vesa-Pekka Palmu
# Copyright:: Copyright (c) Vesa-Pekka Palmu
# License::		Licensed under GPL v3, see LICENSE.md

# Get the display history for a given display or slide
# Since this controller is nested on slides and displays we
# can deal with both cases here
class HistoryController < ApplicationController
  def index
    if params[:display_id].present?
      # We show all slides shown on given display
      @display = Display.find(params[:display_id])
      @all_slides = @display.display_counts.joins(:slide)
                            .order("count_all desc")
                            .group("slides.name", "slides.id").count
      render :index_by_display
    else
      # We show when the given slide has been shown
      @slide = Slide.find(params[:slide_id])
      @displays = @slide.display_counts.joins(:display).order("count_all desc")
                        .group("displays.name", "displays.id").count
      render :index_by_slide
    end
  end

  # Show detailed information when a given slide has been shown on
  # a given display
  def show
    @display = Display.find(params[:display_id])
    @slide = Slide.find(params[:id])
    @display_counts = @display.display_counts.where(slide_id: @slide.id)
                              .order(updated_at: :asc)
  end

  # Clear the history for a given display
  def clear
    display = Display.find(params[:display_id])

    # Check for access
    raise ApplicationController::PermissionDenied unless display.admin? current_user

    display.display_counts.delete_all
    flash[:notice] = "Cleared slide history for #{display.name}."
    redirect_to display_history_index_path(display)
  end
end

app/helpers/history_helper.rb
# frozen_string_literal: true

# ISK - A web controllable slideshow system
#
# Author::    Vesa-Pekka Palmu
# Copyright:: Copyright (c) 2012-2013 Vesa-Pekka Palmu
# License::   Licensed under GPL v3, see LICENSE.md

module HistoryHelper
  # First slide shown on the display
  def display_first_slide(d)
    first_shown = d.display_counts.order(updated_at: :asc).first
    l first_shown.updated_at, format: :short
  end

  def slide_first_display(s)
    first_shown = s.display_counts.order(updated_at: :asc).first
    timestamp = l first_shown.updated_at, format: :short
    return "#{timestamp} on display #{link_to first_shown.display.name, display_path(first_shown.display)}".html_safe
  end
end

app/views/history/_navigation.html.slim
- if @display.present?
	li = link_to icon('fas', 'list', 'List displays'), displays_path
	li = link_to icon('fas', 'info-circle', 'Display details'), display_path(@display)
	li class=active_action?('index') = link_to 'Display slide history', display_history_index_path(@display)
	- if @display.admin? current_user
		li = link_to 'Clear history', clear_display_history_index_path(@display), method: :post
- if @slide.present?
	li = link_to icon('fas', 'list', 'List slides'), slides_path
	li = link_to icon('fas', 'info-circle', 'Slide details'), slide_path(@slide)
	li class=active_action?('index')  = link_to 'Slide display history', slide_history_index_path(@slide)

app/views/history/index_by_display.html.slim
div.row
	h1 Slide history for display: #{@display.name}
	
	- if @display.display_counts.present?
		div.col-md-6.col-lg-5
			h2 Totals
			p This display has shown #{@display.display_counts.count} slides since #{display_first_slide(@display)}
			
			h2 All slides shown
			p This display has shown the following slides, ordered by number of times shown:
			
			ul
				- @all_slides.each_pair do |slide, times|
					li
						=> link_to slide.first, slide_path(slide.last)
						' shown #{times} times.
						=< link_to "Detailed history", display_history_path(@display, slide.last)
			
		div.col-md-6.col-lg-5
			h2 10 most recent slides shown
			div.panel-group
				- @display.display_counts.order(updated_at: :desc).limit(10).each do |dc|
					div.panel.panel-default.panel-slide
						div.panel-heading = dc.slide.name
						div.panel-body
							= slide_preview_to_show_tag dc.slide
						div.panel-footer
							'Shown at #{I18n.l(dc.updated_at, :format => :short)}
							= link_to 'Detailed history', display_history_path(@display, dc.slide), class: 'btn btn-primary'

	- else
		div.alert.alert-warning
			p No slides have been shown on this display!

app/views/history/index_by_slide.html.slim
div.row
	h1 Display history for slide #{@slide.name}

	- if @slide.display_counts.present?
		div.col-sm-6.col-md-4.col-lg-3
			h2 Totals
			p 
				'This slide has been shown #{@slide.display_counts.count} times. 
				'Of them #{@slide.display_counts.where(live: true).count} were on live displays.
				'It has been first shown at #{slide_first_display(@slide)}.
		
		div.col-sm-6.col-md-4.col-lg-3
			h2 Last 10 times this slide has been shown
	
			ul
				- @slide.display_counts.limit(10).each do |dc|
					li
						' Shown on #{link_to dc.display.name, display_path(dc.display)} at #{l dc.updated_at, format: :short}
		
		div.col-sm-6.col-md-4.col-lg-3
			h2 Per display history
	
			p This slide has been shown on the following displays
	
			ul
				- @displays.each_pair do |d,count|
					li
						' Shown on #{link_to d.first, display_path(d.last)} for #{count} total times.
						=< link_to "Detailed history", display_history_path(d.last, @slide)
	
	- else
		div.alert.alert-warning No slides have been shown on this display!

app/views/history/show.html.slim
div.row
	h1 Detailed history for display "#{@display.name}" and slide "#{@slide.name}"

	p 
		'The display #{link_to @display.name, display_path(@display)} has shown the slide
		'#{link_to @slide.name, slide_path(@slide)} #{@display_counts.count} times.
	p
		'The slide has been shown at:
		ol.display_counts
			- @display_counts.each do |dc|
				li class=(dc.live ? 'live' : 'not_live') = I18n.l(dc.updated_at, :format => :short)