config/routes.rb
Isk::Application.routes.draw do

  root to: "slides#index"

  get "monitor", to: "monitor#index"
  get "/isk_general" => "tubesock#general"

  concern :acl do
    resource :permission, only: [:create, :destroy]
  end

  resources :displays do
    concerns :acl
    resources :history, only: [:index, :show] do
      collection do
        post "clear"
      end
    end

    member do
      get "presentation"
      get "slide_queue"
      post "sort_queue"
      post "remove_override"
      post "clear_queue"
      put "update_override"
      get "dpy_control"
      get "websocket"
      get "dpy"
      get "dpy_local_control"
    end

    collection do
      post "hello"
    end
  end

  resources :events, except: :destroy do
    member do
      post "generate_images"
    end

    collection do
    end
  end

  resources :groups do
    concerns :acl

    member do
      post "sort", as: "sort"
      get "add_slides"
      post "adopt_slides"
      post "hide_all"
      post "publish_all"
      post "add_to_override"
      get "download_slides"
    end
  end

  resource :login do
  end

  resources :presentations do
    concerns :acl

    member do
      post "sort", as: "sort"
      post "add_group"
      post "remove_group"
      get "preview"
      post "add_to_override"
    end

    collection do
    end
  end

  resources :schedules do
    member do
    end

    collection do
    end
  end

  resources :slides do
    concerns :acl
    resources :history, only: [:index, :show] do
      collection do
        post "clear"
      end
    end

    resource :image, only: [:show]

    member do
      get "preview"
      get "full"
      get "svg_data"
      post "svg_data" => :svg_save, as: "svg_save"
      post "ungroup"
      post "undelete"
      post "hide"
      post "to_inkscape"
      post "to_simple"
      post "add_to_group"
      post "add_to_override"
      post "clone"
      get "thumb"
    end

    collection do
    end
  end

  resources :templates do
    member do
      post :sort
    end

    collection do
    end
  end

  resources :tickets do
    member do
    end

    collection do
    end
  end

  resources :users do
    member do
      get "roles"
      post "grant"
    end

    collection do
    end

    resources :tokens, only: [:create, :destroy]
  end
end

app/models/group.rb
# frozen_string_literal: true

# ISK - A web controllable slideshow system
#
# Author::    Vesa-Pekka Palmu
# Copyright:: Copyright (c) 2012-2013 Vesa-Pekka Palmu
# License::   Licensed under GPL v3, see LICENSE.md

class Group < ApplicationRecord
  belongs_to :master_group
  belongs_to :presentation
  has_many :slides, through: :master_group
  has_many :displays, through: :presentation

  include RankedModel
  ranks :position, with_same: :presentation_id

  delegate :name, to: :master_group

  # Touch associated displays
  after_save :update_timestamps
  after_destroy :update_timestamps

  # Send websocket messages on create and update
  include WebsocketMessages

  def to_hash
    hash = Hash.new
    hash[:name] = name
    hash[:id] = id
    hash[:master_id] = master_group.id
    hash[:position] = position
    hash[:total_slides] = master_group.slides.published.count
    hash[:created_at] = master_group.created_at.to_i
    hash[:updated_at] = master_group.updated_at.to_i
    hash[:slides] = Array.new
    public_slides.each do |s|
      hash[:slides] << s.to_hash(presentation.delay)
    end
    return hash
  end

  # The position of this group in a presentation
  # RankedModel uses sparse indexes in the postion column, so se need to do sql magic.
  def presentation_position
    Group.where(presentation_id: presentation_id).where("position < ?", position).count
  end

  def public_slides
    slides.where(public: true)
  end

  def cache_tag
    "group_#{id}"
  end

private

  def update_timestamps
    touch_by_presentation(presentation_id)
    touch_by_presentation(presentation_id_was) if changed.include? "presentation_id"
  end

  # We need to proganate timestamps down the presentation chain for
  # the dpy, as it updates it's data based on timestamps
  def touch_by_presentation(p_id)
    d = Display.joins(:presentation).where(presentations: { id: p_id })
    d.update_all(updated_at: Time.now.utc)

    Presentation.where(id: p_id).update_all(updated_at: Time.now.utc)
  end
end

app/controllers/groups_controller.rb
# frozen_string_literal: true

# ISK - A web controllable slideshow system
#
# Author::		Vesa-Pekka Palmu
# Copyright:: Copyright (c) 2012-2013 Vesa-Pekka Palmu
# License::		Licensed under GPL v3, see LICENSE.md

class GroupsController < ApplicationController
  # ACL filters
  before_action :require_create, only: [:new, :create]
  before_action :require_admin, only: [:publish_all, :hide_all, :grant, :deny]

  # Get list of all groups in the current event
  def index
    @groups = MasterGroup.current.defined_groups.reorder(Arel.sql("LOWER(name)"))
  end

  # Show detailed information about a group
  def show
    @group = MasterGroup.find(params[:id])
  end

  # Edit a group, we need to check edit priviledges and
  # dissallow editing of internal groups
  def edit
    @group = MasterGroup.find(params[:id])

    if @group.internal
      # Do not allow editing of internal groups
      flash[:error] = "Can't edit internal groups"
      redirect_to group_path(@group)
      return
    end
    require_edit @group
  end

  def update
    @group = MasterGroup.find(params[:id])

    if @group.internal
      # Do not allow editing of internal groups
      flash[:error] = "Can't edit internal groups"
      redirect_to group_path(@group)
      return
    end

    require_edit @group

    # Handle prizegroup data
    @group.data = params[:master_group][:data] if @group.is_a? PrizeGroup

    if @group.update_attributes(master_group_params)
      flash[:notice] = "Group was successfully updated."
      redirect_to group_path(@group)
    else
      render action: :edit
    end
  end

  # Set all slides in the groups to public
  def publish_all
    @group = MasterGroup.find(params[:id])
    @group.publish_slides
    redirect_to group_path(@group)
  end

  # Hide all slides in the group
  def hide_all
    @group = MasterGroup.find(params[:id])
    @group.hide_slides
    redirect_to group_path(@group)
  end

  # Change the order of slides in the group, used with jquerry sortable widget.
  def sort
    @group = MasterGroup.find(params[:id])
    require_edit @group

    s = @group.slides.find(params[:element_id])
    render text: "Invalid request data", status: 400 unless s

    s.position_position = params[:element_position]
    s.save!
    @group.reload
    respond_to do |format|
      format.js { render :sortable_items }
    end
  end

  # Delete a group, all contained slides will become ungrouped
  def destroy
    @group = MasterGroup.find(params[:id])
    require_edit @group
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_path }
      format.js
    end
  end

  # Add multiple slides to group, render the selection form for all
  # ungrouped slides
  def add_slides
    @group = MasterGroup.find(params[:id])
    require_edit @group

    @slides = current_event.ungrouped.slides.current.to_a
  end

  # Add multiple slides to group
  def adopt_slides
    @group = MasterGroup.find(params[:id])
    require_edit @group
    added = []
    params[:add_slides].each do |id|
      s = current_event.ungrouped.slides.find(id)
      added << s.name
      s.master_group_id = @group.id
      s.save!
    end

    if added.present?
      flash[:notice] = "Added #{added.size} #{'slide'.pluralize(added.size)}"\
                       " to group #{@group.name}."
    end

    redirect_to group_path(@group)
  end

  def new
    @group = MasterGroup.new
  end

  # FIXME: move creation logic to models
  def create
    if params[:prize]
      # Create new prize ceremony group
      @group = PrizeGroup.new(master_group_params)
      @group.event = current_event
      puts "foo"
      puts params[:master_group][:data]
      puts "bar"
      puts @group.data
    else
      # Create normal group
      @group = MasterGroup.new(master_group_params)
      @group.event = current_event
    end

    if @group.save
      flash[:notice] = "Group created."
      @group.authorized_users << current_user unless MasterGroup.admin? current_user
      redirect_to group_path(@group)
    else
      flash[:error] = "Error creating group"
      render :new
      return
    end
  end

  # Download the slides as a zip archive
  def download_slides
    group = MasterGroup.find(params[:id])
    send_data group.zip_slides, filename: "group_#{group.id}_#{group.name}.zip"
  end

  # Add all slides on this group to override on a display
  # FIXME: effect!
  def add_to_override
    group = MasterGroup.find(params[:id])
    display = Display.find(params[:override][:display_id])
    raise ApplicationController::PermissionDenied unless display.can_override?(current_user)
    duration = params[:override][:duration].to_i

    group.slides.each do |s|
      display.add_to_override(s, duration)
    end
    flash[:notice] = "Added group #{group.name} to override"\
                     " on display #{display.name}"
    redirect_to group_path(group)
  end

private

  # Whitelist the parameters for creating and editing groups
  def master_group_params
    params.required(:master_group).permit(:name, :effect_id,
      data: [:template_id, :title, awards: [:name, :by, :pts]])
  end

  def require_create
    raise ApplicationController::PermissionDenied unless MasterGroup.can_create?(current_user)
  end

  def require_admin
    raise ApplicationController::PermissionDenied unless MasterGroup.admin?(current_user)
  end
end

app/helpers/groups_helper.rb
# frozen_string_literal: true

# ISK - A web controllable slideshow system
#
# Author::		Vesa-Pekka Palmu
# Copyright:: Copyright (c) 2012-2013 Vesa-Pekka Palmu
# License::		Licensed under GPL v3, see LICENSE.md

module GroupsHelper
  # Cache key for group reated stuff
  def group_cache_key(group)
    group.cache_key + current_user.cache_key
  end

  # Construct a link to a group with basic group infor
  def group_link_tag(g)
    html = "Group: #{link_to(g.name, group_path(g), name: "group_#{g.id}")}"\
           " Slides: #{g.slides.published.count}/#{g.slides.count}"
    return html.html_safe
  end

  def group_download_slides_link(group)
    link_text = icon "fas", "download", "Slides (zip)"
    link_to link_text, download_slides_group_path(group), class: "btn btn-primary"
  end

  def group_edit_link(group)
    link_to edit_link_text, edit_group_path(group),
            class: "btn btn-primary",
            title: "Edit slide order and group metadata."
  end
end

app/views/groups/_form.html.slim
= f.text_field :name
= f.collection_select(:effect_id, Effect.all, :id, :name, {include_blank: true, label: 'Slide transition effect'})

app/views/groups/_navigation.html.slim
li class=active_action?('index') = link_to icon('fas', 'list', 'List groups'), groups_path
- if MasterGroup.can_create? current_user
	li class=active_action?('new') = link_to icon('fas', 'plus', 'New group'), new_group_path
- if @group.present? && !@group.new_record?
	li class=active_action?('show') = link_to details_link_text, group_path(@group)
	li = link_to icon('fas', 'download', 'Slides (zip)'), download_slides_group_path(@group)
	- if @group.can_edit? current_user
		li class=active_action?('edit') = link_to edit_link_text, edit_group_path(@group)
		li = link_to 'Hide all slides', hide_all_group_path(@group), method: :post
		li = link_to 'Publish all slides', publish_all_group_path(@group), method: :post
		li = link_to icon('fas', 'plus', 'Add slides'), add_slides_group_path(@group)
		li = link_to icon('fas', 'times-circle', 'Delete'), group_path(@group), method: :delete,
			data: {confirm: "Are you sure you want to delete this group? \
			All slides in this group will be marked as deleted."}

app/views/groups/_override_pane.html.slim
- if Display.can_override(current_user).present?
	div.tab-pane#overrides
		h2 Add all slides in this group to override on a display
		= bootstrap_form_for :override, url: add_to_override_group_path(@group), layout: :horizontal,
			 label_col: 'col-sm-2', control_col: 'col-sm-4' do |f|
			= f.collection_select(:display_id, Display.can_override(current_user), :id, :name)
			div.form-group
				= f.label :duration, 'Duration (seconds)',class: 'control-label col-sm-2'
				div.col-sm-4
					div.input-group.spinner
						= f.text_field_without_bootstrap :duration, class: 'form-control', value: 5.minutes
						div.input-group-btn-vertical
							a.btn.btn-default
								i.fa.fa-caret-up
							a.btn.btn-default
								i.fa.fa-caret-down
			= f.form_group do
				= f.primary 'Add to override'

app/views/groups/_presentations_pane.html.slim
div.tab-pane.active#presentations
	h2 Presentations
	- if @group.presentations.present?
		p This group is part of the following presentations:
		ul
			- @group.presentations.each do |p|
				li = link_to p.name, presentation_path(p)
	- else
		p This group doesn't belong to any presentation.

app/views/groups/_prize_form.html.slim
div.col-md-4
	h3 Prize awards

	- data = (@group.is_a?(PrizeGroup) ? @group.data : PrizeGroup::DefaultData)
	= f.fields_for :data do |ff|
		= ff.collection_select(:template_id, current_templates, :id, :name, {selected: data[:template_id].to_i})
		= ff.text_field :title, value: data[:title], label: 'Subheading for generated slides'

	table.awards.table
		tr
			th Place
			th Name
			th By
			th Points
		- data[:awards].each_with_index do |a, i|
			tr
				td = "#{i + 1}#{(i+1).ordinal}"
				td = text_field_tag 'master_group[data][awards][][name]', a[:name], class: 'form-control'
				td = text_field_tag 'master_group[data][awards][][by]', a[:by], class: 'form-control'
				td = text_field_tag 'master_group[data][awards][][pts]', a[:pts], class: 'form-control'

app/views/groups/_prizegroup_pane.html.slim
- if @group.is_a? PrizeGroup
	div.tab-pane#prize_group
		h2 Prize group data
		p Title: #{@group.data[:title]}
		ol
			- @group.data[:awards].each do |d|
				li
					b Name:
					= d[:name]
					b By:
					= d[:by]
					b Points:
					= d[:pts]

app/views/groups/_sortable_slides.html.slim
- group.slides.each do |slide|
	li.sortable id="slide_#{slide.id.to_s}" class=(slide.public ? 'slide-public' : 'slide-hidden')
		div.panel.panel-default.sortable-slide
			div.panel-heading
				span.handle.fa.fa-arrows-v
				= link_to slide.name, slide_path(slide.id)
			div.panel-body
				= slide_preview_to_show_tag slide
			div.panel-footer
				= slide_ungroup_button slide
		

app/views/groups/add_slides.html.slim
h1 Add slides to group: #{@group.name}
p 
	| Here you can add ungrouped slides to this group. 
	   All selected slides will be added to the end of this group.

= bootstrap_form_for @group, url: adopt_slides_group_path(@group.id), method: :post do |f|
	= f.primary 'Add slides to group'
	table#slide_selection.table
		colgroup
			col.slide-name
			col.slide-preview
			col.checkbox
		tbody
			tr
				th Slide name
				th Slide preview
				th Add this slide?
			- @slides.each do |s|
				tr
					td = s.name
					td = slide_preview_image_tag s
					td = check_box_tag 'add_slides[]', s.id, false, class: 'form-control'
	= f.primary 'Add slides to group'

app/views/groups/destroy.js.erb
$('div#<%=@group.id.to_s%>.panel-iskgroup').remove()

app/views/groups/edit.html.slim
div.row
	h1 Edit group: #{@group.name}
	
	= bootstrap_form_for @group, url: group_path(@group) do |f|
		= f.error_messages
		div.col-md-4
			h2 Group metadata
			= render partial: 'form', locals: {f: f}
			
		- if @group.is_a? PrizeGroup
			= render partial: 'prize_form', locals: {f: f}
		div.col-md-8
			= f.primary 'Update group'
	
	div.col-md-12
		h2 Reorder slides in this group
		p Drag slides to reorder them.
		div.sortable-container.panel.panel-primary
			div.panel-heading Slides in this group
			div.panel-body
				ul#slides.sortable.panel-group.list-group data-sortable=sort_group_path(@group)
					= render partial: 'sortable_slides', locals: {group: @group}

app/views/groups/index.html.slim
h1 All groups in current event (#{current_event.name})

= render partial: 'shared/group_links'

div.group-list
	= render @groups

app/views/groups/new.html.slim
h1 Create a new group

div.panel.panel-default
	ul.nav.nav-tabs
		li.active: a data-toggle="tab" href="#normal": span Normal group
		li: a data-toggle="tab" href="#prize": span Prize ceremony
	
	div.tab-content.panel-body
		div#normal.tab-pane.active
			h2 Create a normal group
			= bootstrap_form_for @group, url: groups_path(@group) do |f|
				= render partial: 'form', locals: {f: f}
				= f.primary 'Create group'
	
		div#prize.tab-pane
			h2 Create a prize ceremony group
			p 
				| This is a special group intended for price ceremonies.
				| It will automatically generate slides with all given places, revealing
				| the names in reverse order.
			= bootstrap_form_for @group, url: groups_path(@group) do |f|
				= f.error_messages
				= hidden_field_tag :prize, true
				= render partial: 'form', locals: {f: f}
				= render partial: 'prize_form', locals: {f: f}
				= f.primary 'Create prize group'

app/views/groups/show.html.slim
div.row
	h1 Information for group: #{@group.name}
	
	div.col-md-6
		div.panel.panel-default
			ul.nav.nav-tabs
				li.active: a data-toggle="tab" href="#presentations" Presentations
				- if @group.is_a? PrizeGroup
					li: a data-toggle="tab" href="#prize_group" Prize group data
				li: a data-toggle="tab" href="#tickets" Tickets
				- if Display.can_override(current_user).present?
					li: a data-toggle="tab" href="#overrides" Overrides
				li: a data-toggle="tab" href="#authorized_users" Authorized users
			div.tab-content.panel-body
				= render partial: 'presentations_pane'
				= render partial: 'prizegroup_pane'
				= render partial: 'override_pane'
				= tickets_partial(@group)
				= authorized_users(@group)
div.row
		div.col-xs-12
			h2 Slides in this group
			= render partial: 'slides/group', collection: [@group]

app/views/groups/sortable_items.js.erb
$('[data-sortable]').html('<%=j render partial: 'sortable_slides', :locals => {:group => @group}%>');