config/routes.rb
Isk::Application.routes.draw do

  root to: "slides#index"

  get "monitor", to: "monitor#index"
  get "/isk_general" => "tubesock#general"

  concern :acl do
    resource :permission, only: [:create, :destroy]
  end

  resources :displays do
    concerns :acl
    resources :history, only: [:index, :show] do
      collection do
        post "clear"
      end
    end

    member do
      get "presentation"
      get "slide_queue"
      post "sort_queue"
      post "remove_override"
      post "clear_queue"
      put "update_override"
      get "dpy_control"
      get "websocket"
      get "dpy"
      get "dpy_local_control"
    end

    collection do
      post "hello"
    end
  end

  resources :events, except: :destroy do
    member do
      post "generate_images"
    end

    collection do
    end
  end

  resources :groups do
    concerns :acl

    member do
      post "sort", as: "sort"
      get "add_slides"
      post "adopt_slides"
      post "hide_all"
      post "publish_all"
      post "add_to_override"
      get "download_slides"
    end
  end

  resource :login do
  end

  resources :presentations do
    concerns :acl

    member do
      post "sort", as: "sort"
      post "add_group"
      post "remove_group"
      get "preview"
      post "add_to_override"
    end

    collection do
    end
  end

  resources :schedules do
    member do
    end

    collection do
    end
  end

  resources :slides do
    concerns :acl
    resources :history, only: [:index, :show] do
      collection do
        post "clear"
      end
    end

    resource :image, only: [:show]

    member do
      get "preview"
      get "full"
      get "svg_data"
      post "svg_data" => :svg_save, as: "svg_save"
      post "ungroup"
      post "undelete"
      post "hide"
      post "to_inkscape"
      post "to_simple"
      post "add_to_group"
      post "add_to_override"
      post "clone"
      get "thumb"
    end

    collection do
    end
  end

  resources :templates do
    member do
      post :sort
    end

    collection do
    end
  end

  resources :tickets do
    member do
    end

    collection do
    end
  end

  resources :users do
    member do
      get "roles"
      post "grant"
    end

    collection do
    end

    resources :tokens, only: [:create, :destroy]
  end
end

app/models/schedule.rb
# frozen_string_literal: true

# ISK - A web controllable slideshow system
#
# Author::    Vesa-Pekka Palmu
# Copyright:: Copyright (c) 2012-2013 Vesa-Pekka Palmu
# License::   Licensed under GPL v3, see LICENSE.md

class Schedule < ApplicationRecord
  # Relations:
  has_many :schedule_events, -> { order at: :asc }, dependent: :delete_all
  belongs_to :event
  belongs_to :slidegroup, class_name: "MasterGroup", dependent: :destroy, optional: true
  belongs_to :next_up_group, class_name: "MasterGroup", dependent: :destroy, optional: true

  # Allow updating the schedule events in one call
  accepts_nested_attributes_for :schedule_events, allow_destroy: true

  # Validations:
  validates :name, :event, presence: true
  # Validate slide group existance on update, we create them after create
  validates :slidegroup, :next_up_group, presence: true, on: :update

  # Callbacks:
  # Create groups that will contain the slides generated from this schedule
  after_create :create_groups
  # Rename the associated groups if the schedule name changes
  after_update :rename_groups
  # By default assing to the current event
  before_validation :set_event_id, on: :create

  # Return all schedules in the current event
  def self.current
    where(event_id: Event.current.id)
  end

  # Settings for this schedule
  # TODO: Still allow custom per schedule settings?
  def settings
    @_settings ||= event.config[:schedules]
  end

  # Generate schedule slides
  # FIXME: break this into smaller methods...
  def generate_slides
    # Use the schedule name if custom slide header hasn't been defined
    header = slide_header.present? ? slide_header : name

    # Paginate the schedule events into slides
    slide_data = paginate_events(events_array)
    total_slides = slide_data.size
    current_slide = 1

    # Slide description to use on all generated slides
    slide_description = "Automatically generated from schedule #{name} at #{I18n.l Time.now, format: :short}"
    # Make sure there are right amount of slides in our group
    delta = slide_data.count - schedule_slide_count
    if delta.positive?
      add_scheduleslides(slide_data.count - schedule_slide_count)
    elsif delta.negative?
      slidegroup.slides.where(type: ScheduleSlide.sti_name).limit(-delta).each(&:destroy)
    end

    # Find the scheduleslides in our slidegroup
    schedule_slides = slidegroup.slides.where(type: ScheduleSlide.sti_name).to_a

    # Create a array containing a slide and the data to be shown on that slide
    # FIXME: there must be a cleaner way...
    slides = Array.new
    slide_data.each_index do |i|
      slides << [schedule_slides[i], slide_data[i]]
    end

    # Set the data to each corresponding slide
    slides.each do |s|
      if total_slides == 1
        @header = header
      else
        @header = "#{header} #{current_slide}/#{total_slides}"
      end
      slide = s.first
      slide.name = @header
      slide.description = slide_description
      slidegroup.slides << slide
      slide.publish
      slide.save!
      @items = s.last
      # Generate the slide SVG
      slide.create_svg(@header, @items)
      slide.generate_images_later

      current_slide += 1
    end

    slidegroup.publish_slides

    # Generate the "up next" slide if needed
    generate_next_up_slide if next_up && schedule_events.present?
    return true
  end

  def generate_slides_later
    GenerateSlidesJob.perform_later self
  end

private

  # Create the associated groups when a new schedule is created
  def create_groups
    sg = MasterGroup.create(name: "Schedule: #{name} slides", event_id: event_id)
    ung = MasterGroup.create(name: "Schedule: #{name} next up", event_id: event_id)

    self.slidegroup = sg
    self.next_up_group = ung
    self.event_id = Event.current.id unless event_id
    save!
  end

  # Rename the groups containing our slides on update
  def rename_groups
    slidegroup.update_attributes(name: "Schedule: #{name} slides")
    next_up_group.update_attributes(name: "Schedule #{name} next up")
  end

  # Generate a slide with the next EventsPerSlide schedule events
  def generate_next_up_slide
    slide_description = "Next #{settings[:events][:per_slide]} events on schedule #{name}"
    slide_name = next_up_header.present? ? next_up_header : "Next up: #{name}"

    nus = find_or_initialize_next_up_slide
    nus.name = slide_name
    nus.description = slide_description
    @header = slide_name

    slides = paginate_events(events_array(true))
    if slides.empty?
      # Hide the next up slide if there are no more events
      nus.hide
      nus.save!
      nus.generate_images_later
    end
    slides.each do |slide|
      @items = slide
      nus.create_svg @header, @items
      nus.save!
      nus.generate_images_later
      break
    end
    return true
  end

  # Find or create the slide for "next up" slide
  def find_or_initialize_next_up_slide
    if next_up_group.slides.where(type: ScheduleSlide.sti_name).first.present?
      return next_up_group.slides.where(type: ScheduleSlide.sti_name).first!
    end
    slide = ScheduleSlide.new
    next_up_group.slides << slide
    return slide
  end

  # Convenience method for getting the count of schedule slides in our slidegroup
  def schedule_slide_count
    slidegroup.slides.where(type: ScheduleSlide.sti_name).count
  end

  # Add more schedule slides to our slidegroup up to 'number' slides
  def add_scheduleslides(number)
    slide_description = "Automatically generated from schedule #{name} at #{I18n.l Time.now, format: :short}"
    number.times do
      slide = ScheduleSlide.new
      slide.name = name
      slide.description = slide_description
      slidegroup.slides << slide
      slide.save!
    end
  end

  # Form a array of schedule events and inser subheaders for date changes if needed
  def events_array(do_subheaders = true)
    slide_items = Array.new
    last_date = nil

    schedule_events.each do |e|
      # Ignore events that are more than settings[:time_tolerance] in past
      if e.end_time.present?
        next if (e.end_time + settings[:time_tolerance]).past?
      else
        next if (e.at + settings[:time_tolerance]).past?
      end

      # Insert a subheader if next event is in different day
      if do_subheaders && e.at.to_date != last_date
        slide_items << { subheader: e.at.strftime("%A %d.%m."), linecount: 1 }
      end
      slide_items << { name: e.name, time: e.at.strftime("%H:%M"), linecount: e.linecount }
      last_date = e.at.to_date
    end
    return slide_items
  end

  # Create an array containing items for each slide suitable for the template
  # A slide contains at most EventsPerSlide number of events in it
  # If day changes between slides a new header will be added
  # If the new day would have less than self.min_events_on_next_day events after it on the current slide
  # create a new slide.
  def paginate_events(slide_items)
    # Break the events up on slides EventsPerSlide per slide
    slides = Array.new
    this_slide = Array.new
    last_subheader = nil

    slide_items.each do |item|
      if item[:subheader]
        if this_slide.size + min_events_on_next_day > settings[:events][:per_slide]
          slides << this_slide
          this_slide = Array.new
        end
        last_subheader = item
      elsif this_slide.empty? && last_subheader
        this_slide << last_subheader
      end

      if item[:linecount] == 1
        this_slide << item
      else
        if (this_slide.size + item[:linecount]) > settings[:events][:per_slide]
          this_slide.pop if this_slide.last[:subheader]
          slides << this_slide
          this_slide = Array.new
          this_slide << last_subheader
        end
        lines = item[:name].split("\n")
        this_slide << { name: lines.first, time: item[:time] }
        lines.delete_at 0
        (item[:linecount] - 1).times do
          this_slide << { name: lines.first, time: "" }
          lines.delete_at 0
        end
      end

      if this_slide.size >= settings[:events][:per_slide]
        slides << this_slide
        this_slide = Array.new
      end
    end

    slides << this_slide unless this_slide.empty?
    return slides
  end

  def set_event_id
    self.event = Event.current unless event.present?
  end
end

app/controllers/schedules_controller.rb
# frozen_string_literal: true

# ISK - A web controllable slideshow system
#
# Author::    Vesa-Pekka Palmu
# Copyright:: Copyright (c) Vesa-Pekka Palmu
# License::   Licensed under GPL v3, see LICENSE.md

class SchedulesController < ApplicationController
  # TODO: correct ACL
  # We require admin priviledges for all actions for now...
  before_action :require_global_admin

  # List all schedules in the current event
  def index
    @schedules = Schedule.current
  end

  # Show details on given schedule
  def show
    @schedule = Schedule.find(params[:id])
  end

  # Render a form to create a new schedule
  def new
    @schedule = Schedule.new
  end

  # Create a new schedule based on the POST params
  def create
    Schedule.transaction do
      @schedule = Schedule.new(schedule_params)
      if @schedule.save
        flash[:notice] = "Schedule created"
        redirect_to schedule_path(@schedule)
      else
        flash[:error] = "Error creating schedule"
        render :new
        return
      end
    end
  end

  # Render edit form for a schedule
  def edit
    @schedule = Schedule.find(params[:id])
    @new_event = ScheduleEvent.new
  end

  # Update a schedule based on the post parameters
  def update
    @schedule = Schedule.find(params[:id])

    if @schedule.update_attributes(schedule_params)
      @schedule.generate_slides_later
      respond_to do |format|
        format.html do
          flash[:notice] = "Schedule updated"
          redirect_to schedule_path(@schedule)
        end

        format.js do
          @new_event = @schedule.schedule_events.reorder(id: :desc).first
          @message = "Event added: #{@new_event.name}"
          render :update_form
        end
      end
    else
      flash[:error] = "Error updating schedule"
      render :edit
    end
  end

private

  # Whitelist POST parameters for create and update
  def schedule_params
    params.required(:schedule).permit(:name, :max_slides,
                                      :min_events_on_next_day,
                                      :next_up, :slide_header,
                                      :next_up_header,
                                      schedule_events_attributes: [
                                        :id,
                                        :name,
                                        :major,
                                        :at,
                                        :end_time,
                                        :_destroy
                                      ])
  end
end

app/helpers/schedules_helper.rb
# frozen_string_literal: true

# ISK - A web controllable slideshow system
#
# Author::    Vesa-Pekka Palmu
# Copyright:: Copyright (c) 2012-2013 Vesa-Pekka Palmu
# License::   Licensed under GPL v3, see LICENSE.md

module SchedulesHelper
end

app/views/schedules/_form.html.slim
div#schedule-edit-form
	= bootstrap_form_for @schedule do |f|
		div.col-sm-6.col-md-4.col-lg-3
			h2 Metadata and settings

			= f.text_field :name
			= f.text_field :slide_header
			= f.text_field :max_slides
			= f.text_field :min_events_on_next_day
			= f.text_field :next_up
			= f.text_field :next_up_header

			= f.primary

	- unless @schedule.new_record?
		div.col-md-10
			h2 Add a new event
			= form_for @schedule, remote: true, html: {class: 'add_event_form'} do |f|
					=f.fields_for :schedule_events, @new_event do |ff|
						table.schedule_events_edit
							tr
								th Time
								th End time
								th Name
								th -
							tr
								td = ff.datetime_select :at
								td = ff.datetime_select :end_time
								td = ff.text_field :name, class: 'form-control'
								td = ff.check_box :major, class: 'form-control'
								td = ff.submit 'Add event', class: 'btn btn-primary'
	- if @schedule.schedule_events.present?
		div.col-md-10
			= bootstrap_form_for @schedule do |f|
				h2 Schedule events
				table.schedule_events_edit
					tr
						th Time
						th Name
						th Major
						th Delete
					= f.fields_for :schedule_events do |e|
						tr
							td = e.datetime_select_without_bootstrap :at, class: 'form-control'
							td = e.text_field_without_bootstrap :name, class: 'form-control'
							td = e.check_box_without_bootstrap :major, class: 'form-control'
							td = e.check_box_without_bootstrap :_destroy, class: 'form-control'
				= f.primary

app/views/schedules/_navigation.html.slim
li class=active_action?('index') = link_to icon('fas', 'list', 'List schedules'), schedules_path
li class=active_action?('new') = link_to icon('fas', 'plus', 'New schedule'), new_schedule_path
- if @schedule.present? && !@schedule.new_record?
	li class=active_action?('show') = link_to details_link_text, schedule_path(@schedule)
	li class=active_action?('edit') = link_to edit_link_text, edit_schedule_path(@schedule)

app/views/schedules/_schedule.html.slim
div.col-md-4.col-sm-6.col-lg-3
	div.panel-schedule.panel.panel-primary id="schedule_#{schedule.id}"
		div.panel-heading
			= link_to schedule.name, schedule_path(schedule)
		div.panel-body
			ul
				li Events in this schedule: #{schedule.schedule_events.count}
				li
					| Group for generated slides:
					=< link_to schedule.slidegroup.name, group_path(schedule.slidegroup)
				li
					| Maximum number of generated slides:
					=< schedule.max_slides == -1 ? 'Unlimited' : schedule.max_slides
				li Generate "next up" -slides: #{schedule.next_up ? 'Yes' : 'No'}
				li
					| Group for "next up" -slides:
					=< link_to schedule.next_up_group.name, group_path(schedule.next_up_group)
		div.panel-footer
			div.btn-group.btn-group-sm
				= link_to icon('fas', 'info-circle', 'Details'), schedule_path(schedule), class: 'btn btn-primary'
				= link_to icon('fas', 'edit', 'Edit'), edit_schedule_path(schedule), class: 'btn btn-primary'

app/views/schedules/_schedule_event.html.slim
tr
	td = l schedule_event.at, format: :short
	td = schedule_event.end_time.present? ? l( schedule_event.end_time, format: :short) : "-"
	td = schedule_event.name

app/views/schedules/edit.html.slim
div.row
	h1 Editing schedule: #{@schedule.name}

	= render partial: 'form'

app/views/schedules/index.html.slim
div.row
	h1 Listing all schedules

	= render @schedules

app/views/schedules/new.html.slim
h1 Create new schedule

= form_for @schedule do |f|
	= f.error_messages
	= render partial: 'form'

app/views/schedules/show.html.slim
div.row
	h1 Schedule information for: #{@schedule.name}

	= render @schedule

	div.col-sm-6
		div.panel.panel-default
			div.panel-heading Scheduled events
			div.panel-body
				- if @schedule.schedule_events.present?
					table.schedule_events.table
						tr
							th Time
							th End time
							th Name
						- @schedule.schedule_events.each do |event|
							= render partial: 'schedule_event', object: event
				- else
					div.alert.alert-warning.col-xs-8 This schedule doesn't contain any events!

app/views/schedules/update_form.js.erb
$('#schedule-edit-form').replaceWith('<%=j render :partial => 'form' %>');
var message = noty({
	text: '<%=@message%>',
	type: 'Information',
	timeout: 5000
})