config/routes.rb
Isk::Application.routes.draw do

  root to: "slides#index"

  get "monitor", to: "monitor#index"
  get "/isk_general" => "tubesock#general"

  concern :acl do
    resource :permission, only: [:create, :destroy]
  end

  resources :displays do
    concerns :acl
    resources :history, only: [:index, :show] do
      collection do
        post "clear"
      end
    end

    member do
      get "presentation"
      get "slide_queue"
      post "sort_queue"
      post "remove_override"
      post "clear_queue"
      put "update_override"
      get "dpy_control"
      get "websocket"
      get "dpy"
      get "dpy_local_control"
    end

    collection do
      post "hello"
    end
  end

  resources :events, except: :destroy do
    member do
      post "generate_images"
    end

    collection do
    end
  end

  resources :groups do
    concerns :acl

    member do
      post "sort", as: "sort"
      get "add_slides"
      post "adopt_slides"
      post "hide_all"
      post "publish_all"
      post "add_to_override"
      get "download_slides"
    end
  end

  resource :login do
  end

  resources :presentations do
    concerns :acl

    member do
      post "sort", as: "sort"
      post "add_group"
      post "remove_group"
      get "preview"
      post "add_to_override"
    end

    collection do
    end
  end

  resources :schedules do
    member do
    end

    collection do
    end
  end

  resources :slides do
    concerns :acl
    resources :history, only: [:index, :show] do
      collection do
        post "clear"
      end
    end

    resource :image, only: [:show]

    member do
      get "preview"
      get "full"
      get "svg_data"
      post "svg_data" => :svg_save, as: "svg_save"
      post "ungroup"
      post "undelete"
      post "hide"
      post "to_inkscape"
      post "to_simple"
      post "add_to_group"
      post "add_to_override"
      post "clone"
      get "thumb"
    end

    collection do
    end
  end

  resources :templates do
    member do
      post :sort
    end

    collection do
    end
  end

  resources :tickets do
    member do
    end

    collection do
    end
  end

  resources :users do
    member do
      get "roles"
      post "grant"
    end

    collection do
    end

    resources :tokens, only: [:create, :destroy]
  end
end

app/controllers/displays_controller.rb
# frozen_string_literal: true

# ISK - A web controllable slideshow system
#
# This controller handles the managing of remote isk displays.
#
# Author::		Vesa-Pekka Palmu
# Copyright:: Copyright (c) 2012-2013 Vesa-Pekka Palmu
# License::		Licensed under GPL v3, see LICENSE.md

class DisplaysController < ApplicationController
  # Tubesock websockets
  include Tubesock::Hijack

  # ACL filters
  before_action :require_create, only: [:new, :create]
  # We send error messages on ACL violations via the websocket
  skip_before_action :require_login, only: :websocket

  # List all displays
  # We support html or json for the whole list and
  # js for updating the late display warnings on pages.
  def index
    @displays = Display.order(live: :desc, name: :asc)

    respond_to do |format|
      format.js
      format.html
      format.json do
        render json: @displays.collect do |d|
          {
            id: d.id,
            name: d.name,
            status: d.status,
            late: d.late?
          }
        end
      end
    end
  end

  # Get the details on a given display
  # We support html, json for the data serilazation and
  # js for updating the div#display_<id> blocks
  def show
    @display = Display.includes(:presentation, override_queues: :slide)
                      .find(params[:id])

    respond_to do |format|
      format.html
      format.json do
        render json: JSON.pretty_generate(@display.to_hash)
      end
      format.js
    end
  end

  # Delete a display and associated data
  def destroy
    # Only admins can delete displays
    require_admin

    display = Display.find(params[:id])
    display.destroy
    flash[:notice] = "Deleted display id: #{display.id} - #{display.name}"
    redirect_to displays_path, status: :see_other
  end

  def new
    @display = Display.new
  end

  def create
    @display = Display.new(display_params)

    if @display.save
      flash[:notice] = "Display created."
      redirect_to display_path(@display)
    else
      flash.now[:error] = "Error creating display."
      render action: :new
    end
  end

  # Render the edit form for a given display
  def edit
    @display = Display.find(params[:id])
    require_edit @display
  end

  # Update a given display
  # We support html and js, that updates the div#display_<id> block
  def update
    @display = Display.find(params[:id])
    require_edit @display

    if @display.update_attributes(display_params)
      respond_to do |format|
        format.html do
          flash[:notice] = "Display was successfully updated."
          redirect_to display_path(@display), status: :see_other
        end
        format.js { render :show }
      end
    else
      flash.now[:error] = "Error updating display."
      render action: :edit
      return
    end
  end

  # FIXME: create a nested override controller
  def update_override
    oq = OverrideQueue.find(params[:id])
    require_edit oq.display

    oq.duration = params[:override_queue][:duration]
    oq.save!
    flash[:notice] = "Duration was changed"
    redirect_back fallback_location: root_path
  end

  def remove_override
    oq = OverrideQueue.find(params[:id]).destroy
    require_override oq.display

    flash[:notice] = "Removed slide from override queue"
    redirect_back fallback_location: root_path
  end

  def clear_queue
    @display = Display.find(params[:id])
    require_override @display
    @display.override_queues.destroy_all

    flash[:notice] = "Override queue cleared."
    redirect_back fallback_location: root_path
  end

  # Remote control for iskdpy via javascript and websockets
  def dpy_control
    @display = Display.find(params[:id])
  end

  # The webgl display
  def dpy
    @display = Display.find(params[:id])
    raise PermissionDenied unless require_display_control(@display)
    render layout: false
  end

  # FIXME: this logic needs to go to the model
  def sort_queue
    @display = Display.find(params[:id])
    require_edit @display
    oq = @display.queue.find(params[:element_id])
    render text: "Invalid request, try refreshing", status: :bad_request unless oq

    oq.position_position = params[:element_position]
    oq.save!
    @display.reload
    respond_to do |format|
      format.js { render :sortable_items }
    end
  end

  # Websocket connection for communication with displays
  def websocket
    @display = Display.find(params[:id])

    hijack do |tubesock|
      # Listen on its own thread
      redis_thread = Thread.new do
        # Needs its own redis connection to pub
        # and sub at the same time
        Redis.new(Rails.configuration.x.redis).subscribe @display.websocket_channel do |on|
          on.message do |_channel, message|
            tubesock.send_data message
          end
        end
      end

      tubesock.onopen do
        unless current_user
          tubesock.send_data ["error", "forbidden", {}].to_json
          redis_thread.kill
          tubesock.close
        end
      end

      tubesock.onmessage do |m|
        # Clear the query cache before each action
        # Since this is a persistent thread the cache doesn't
        # get reset automatically.
        ActiveRecord::Base.connection.clear_query_cache
        @display.reload

        Rails.logger.debug "Got websocket message: #{m}"
        # Parse the message
        msg = IskMessage.from_json(m)
        # Instument the action for logging
        instrument_action(msg) do
          # we only care about commands
          break unless msg.object == "command"
          case msg.type
          when "get_data"
            # Request to get the serialization of a display
            # We only reply to the requestor
            msg = IskMessage.new("display", "data", @display.to_hash)
            tubesock.send_data msg.encode
          when "goto_slide"
            # Command that tells the display to change to a specified slide
            raise PermissionDenied unless require_display_control(@display)
            msg.object = "display"
            msg.type = "goto_slide"
            msg.send @display.websocket_channel
          when "start"
            # Display tells that it is starting up
            raise PermissionDenied unless require_display_control(@display)

            # Detect WPE / Raspberry pi displays
            @display.wpe = request.user_agent.present? && request.user_agent.include?("WPE")
            @display_connection = true
            @display.status = "running"
            @display.ip = request.remote_ip
            @display.last_hello = Time.now
            @display.save!
            msg = IskMessage.new("display", "start", {})
            msg.send @display.websocket_channel
          when "current_slide"
            # Display informs us that it has changed to a specified slide
            raise PermissionDenied unless require_display_control(@display)
            # Check if the display changed to a slide from override queue
            if msg.payload[:override_queue_id]
              group = -1
              slide = @display.override_queues.find(msg.payload[:override_queue_id]).slide.id
            else
              group = msg.payload[:group_id]
              slide = msg.payload[:slide_id]
            end
            # Validate that the slide was part of the displays slideset
            msg.object = "display"
            if @display.set_current_slide(group, slide)
              msg.type = "current_slide"
              msg.send @display.websocket_channel
            else
              msg.type = "error"
              msg.payload = { error: "Invalid slide specified" }
              tubesock.send_data msg.encode
            end
          when "slide_shown"
            # Display has finished showing a slide
            # We only care about this if the slide was from the override queue
            raise PermissionDenied unless require_display_control(@display)
            @display.override_shown(msg.payload[:override_queue_id]) if msg.payload[:override_queue_id]

            msg.object = "display"
            msg.type = "slide_shown"
            msg.send @display.websocket_channel
          when "shutdown"
            # Display is performing a controlled shutdown
            raise PermissionDenied unless require_display_control(@display)

            @display_connection = false
            @display.status = "disconnected"
            @display.save!
            msg = IskMessage.new "display", "shutdown", {}
            msg.send @display.websocket_channel
          when "error"
            # Display reports that it has encountered an error
            @display.add_error msg.payload[:error]
            @display.save!
          when "ping"
            # Simple ping-pong so the display can test that the connection is up
            msg.object = "display"
            msg.type = "pong"
            @display.ping
            @display.state.save!
            tubesock.send_data msg.encode
          end
        end
      end

      # Error handlers
      # We just close the socket on all errors and if this connection was
      # from a display we mark its state as invalid.
      tubesock.onerror do |e, data|
        if e.is_a? PermissionDenied
          tubesock.send_data ["error", "forbidden", {}].to_json
        else
          Rails.logger.error "Error handling websocket message #{data}\n\tException: #{e.inspect}\n\tBacktrace:\n\t\t#{e.backtrace.join("\n\t\t")}"
        end
        redis_thread.kill
        tubesock.close
        if @display_connection
          @display.status = "error"
          @display.save!
        end
      end

      tubesock.onclose do
        # stop listening when client leaves
        redis_thread.kill
        if @display_connection
          @display.status = "error"
          @display.save!
        end
      end
    end
  end

private

  # Instrument the websocket actions for logging
  def instrument_action(msg)
    options = {
      action: msg.object,
      ip: request.remote_ip,

app/helpers/displays_helper.rb
# frozen_string_literal: true

# ISK - A web controllable slideshow system
#
# Author::		Vesa-Pekka Palmu
# Copyright:: Copyright (c) 2012-2013 Vesa-Pekka Palmu
# License::		Licensed under GPL v3, see LICENSE.md

module DisplaysHelper
  # Links to the details for all late displays
  def late_display_warning(d)
    link_text = "#{d.name} (#{d.ip}) is more than #{Display::TIMEOUT} minutes late!"
    link_to link_text, display_path(d), class: "alert-link"
  end

  def display_clear_queue_button(d)
    link_to "Clear override queue", clear_queue_display_path(d),
            class: "btn btn-danger", title: "Clear all slides from the override queue",
            data: { confirm: "Clear all slides in the override queue?" },
            method: :post
  end

  # Link to displays#destroy if user has sufficient access
  def display_destroy_button(d)
    return unless d.admin?(current_user)
    link_to icon("fas", "times-circle", "Delete"), display_path(d),
            data: {
                    confirm: "Are you sure you want to delete the display"\
                             " \"#{d.name}\", this cannot be undone?"
                  },
            title: "Delete this display premanently",
            method: :delete, class: "button warning"
  end

  # Set the panel class based on display status
  def display_class(display)
    case display.status
    when "running"
      if display.late?
        panel = "panel-warning"
      else
        panel = "panel-success"
      end
    when "disconnected"
      panel = "panel-default"
    else
      panel = "panel-danger"
    end
    return "#{panel} display-live" if display.live?
    return panel
  end

  # Render the display ping element
  def display_ping(d)
    if d.late?
      html_class = "late"
    else
      html_class = "on_time"
    end

    if d.last_contact_at
      ping_seconds = (Time.now - d.last_contact_at).to_i
      ping_seconds = ">60" if ping_seconds > 60
    else
      ping_seconds = "UNKNOWN"
    end

    return content_tag(:span, "Ping: #{ping_seconds} s.", class: html_class)
  end

  # Render the img element for the current slide image
  def display_current_slide(d)
    if (d.status != "error") && d.current_slide.present?
      image = slide_preview_image_tag d.current_slide
    else
      image = image_tag("display_error.png", class: "preview")
    end
    html_options = {
      title: "Click to show display details",
      class: "slide_preview"
    }

    return link_to image, display_path(d), html_options
  end

  # Render the slide duration as text
  def display_slide_duration(d = @display)
    return "Infinite" if d.current_slide.duration.zero?
    return "#{d.presentation.delay} sec (default)" if d.current_slide.duration == -1
    return "#{d.current_slide.duration} sec"
  end

  # Render the last_contact_at timestamp and the diff to current time
  def display_last_contact(d)
    return "UNKNOWN" unless d.last_contact_at
    time_diff = Time.now - d.last_contact_at
    return "> 24h" if time_diff > 24.hours
    delta = Time.at(time_diff.to_i.abs).utc.strftime "%H:%M:%S"
    return "#{l d.last_contact_at, format: :short} (#{delta} ago)"
  end
end

app/views/displays/_display.html.slim
div.panel-display.panel class=display_class(display) id="display_#{display.id}"
	div.panel-heading
		- if display.wpe
			= image_tag 'raspberry-pi.svg', class: 'wpe-icon'
		- if display.status == 'running' && display.late?
			span.fa.fa-warning title="This display isn't responding!"
		- if display.presentation.blank?
			span.fa.fa-question-circle title="No presentation"
		=< link_to display.name, display_path(display)
	div.panel-body
		= display_current_slide(display)
		div.display_metadata
			ul
				- if display.current_slide.present?
					li
						| Current slide:
						=< link_to display.current_slide.name, slide_path(display.current_slide)
					li
						| Duration:
						=< display_slide_duration(display)
				- else
					li Current slide: Unknown
				- if display.current_group.present?
					li
						| Current group:
						=< link_to display.current_group.name, group_path(display.current_group.master_group)
				- else
					li Current group: Unknown
				li
					- if display.presentation
						| Presentation:
						=< link_to display.presentation.name, presentation_path(display.presentation.id)
					- else
						| Presentation: Not defined
				li Status: #{display.status}
				li Uptime: #{display.uptime}
				li Last contact: #{display_last_contact(display)}
				li = display_ping display
				li Monitored: #{display.monitor ? 'Yes' : 'No'}

	div.panel-footer
		div.btn-group.btn-group-sm
			= cache([display, display.can_edit?(current_user)]) do
				- if display.can_edit? current_user
					= toggle_link_to 'Overrides', display.do_overrides, display_path(display,
						display: {do_overrides: !display.do_overrides}), {method: :put, remote: true}
					= toggle_link_to 'Manual control', display.manual, display_path(display,
						display: {manual: !display.manual}), {method: :put, remote: true}
					= link_to details_link_text, display_path(display), class: 'btn btn-primary'
					= link_to edit_link_text, edit_display_path(display), class: 'btn btn-primary'
					= link_to 'Remote control', dpy_control_display_path(display),	class: 'btn btn-primary'
				- else
					= inactive_toggle 'Overrides', display.do_overrides
					= inactive_toggle 'Manual control', display.manual
					= link_to details_link_text, display_path(display), class: 'btn btn-primary'

app/views/displays/_form.html.slim
= bootstrap_form_for @display do |f|
	= f.error_messages
	= f.text_field :name
	= f.check_box :monitor
	= f.check_box :manual
	= f.check_box :live
	= f.collection_select(:presentation_id, current_event.presentations.order(:name), :id, :name, {include_blank: true})
	= f.primary

app/views/displays/_navigation.html.slim
li class=active_action?('index') = link_to icon('fas', 'list', 'List displays'), displays_path
- if Display.can_create? current_user
	li class=active_action?('new') = link_to icon('fas', 'plus', "New display"), new_display_path
- if @display.present? && !@display.new_record?
	- if @display.can_edit? current_user
		li class=active_action?('edit') = link_to edit_link_text, edit_display_path(@display)
	li class=active_action?('show') = link_to details_link_text, display_path(@display)
	li = link_to 'Slide history', display_history_index_path(@display)
	- if @display.can_edit? current_user
		li class=active_action?('dpy_control') = link_to 'Remote control', dpy_control_display_path(@display)
		li = display_clear_queue_button(@display)
		li = display_destroy_button(@display)

app/views/displays/_sortable_overrides.html.slim
- overrides.each do |o|
	li.sortable id="override_queue_#{o.id}"
		div.panel.panel-default.sortable-slide
			div.panel-heading
				span.handle.fa.fa-arrows-v
				= link_to o.slide.name, slide_path( o.slide.id )
			div.panel-body
				= slide_preview_to_show_tag o.slide
			div.panel-footer
				= bootstrap_form_for o, url: update_override_display_path(o.id), layout: :inline do |f|
					= f.text_field :duration, size: 3, class: 'duration_spinner', label: 'Duration'
					= f.primary 'Change'
					= link_to icon('fas', 'minus', 'Remove'), remove_override_display_path(o.id), class: 'btn btn-danger', method: :post

app/views/displays/dpy.html.slim
doctype 5
html
	head
		title
			| Display: #{@display.name}
			=< "- ISK @ #{request.host}"
		= stylesheet_link_tag :display, media: :all
		= csrf_meta_tags
		link rel="icon" type="image/gif" href="/favicon.gif"
		link rel="icon" type="image/x-icon" href="/favicon.ico"
	body
		div#ISKDPY
			div#bgrs
				img#empty src="/backgrounds/empty.png"
			div#renderer
				div#canvas
				div#override
				div#clock
			div#pres
			div#errors
				div#stopped Display stopped, click to restart...
				div#loggedout title="Access denied or other critical connection error" *
				div#connection title="Connection error" *
		= javascript_include_tag :display

app/views/displays/dpy_control.html.slim
div.row
	div.display-control-header
		h1 Iskdpy remote control interface for display: #{@display.name}
		div.alert.alert-warning.alert-connection
			p Websocket connection lost. Trying to reconnect...
		div.alert.alert-info
			=> help_icon
			| This is the remote control interface for a iskdpy display. You can click on any slide image
			   to instruct the display to go to that slide. You can also use the next and previous buttons
				or left and right buttons.

	div.display-preview
		= render @display
		div.control-buttons.btn-group
			a.btn.btn-primary#previous data-id=@display.id href='#top' #{icon 'fas', 'backward'} Previous
			a.btn.btn-primary#next data-id=@display.id href='#top' Next #{icon 'fas', 'forward'}

	div.display-control#display-control data-id=@display.id data-websocket-url=websocket_display_path(@display)

app/views/displays/edit.html.slim
div.row
	h1 Editing display: #{@display.name}

	div.col-sm-6.col-md-4.col-lg-3
		= render partial: 'form'

div.row
	div.col-md-6.col-lg-5
		h2 Override queue
		p You can drag the slides to sort the queue
		p = display_clear_queue_button(@display)

		div.panel.panel-primary.sortable-container
			div.panel-heading Slides in override queue
			div.panel-body
				ul.sortable#override_queues.panel-group.list-group data-sortable=sort_queue_display_url(@display)
					= render partial: 'sortable_overrides', locals: {overrides: @display.override_queues}

app/views/displays/index.html.slim
h1 Display management

= render @displays

app/views/displays/index.js.erb
$('div#display_warnings').replaceWith('<%=j render :partial => 'shared/display_warnings' %>');
<% if Display.late.present? -%>
	$('#displays_tab').addClass('navbar-warning');
<% else -%>
	$('#displays_tab').removeClass('navbar-warning');
<% end -%>

app/views/displays/new.html.slim
div.row
	h1 Create a new display
	
	div.col-sm-6.col-md-4.col-lg-3
		= render partial: 'form'

app/views/displays/show.html.slim
div.row
	h1 Information for display: #{@display.name} (#{@display.ip})
	
	div.col-md-6.col-lg-5
		div.display_properties
			= render @display
	
	div.col-sm-6.col-md-4.col-lg-3
		div.extra_information
			h2 Detailed status
			ul
				li Status: #{@display.status}
				li IP: #{@display.ip}
				- if @display.last_contact_at
					li Last contact at: #{l @display.last_contact_at, :format => :short}
				- else
					li Last contact at: UNKNOWN
		
				- if @display.last_hello
					li Last initialization at: #{l @display.last_hello, format: :short}
				- else
					li Last initialization at: UNKNOWN
				li State updated at: #{l @display.state_updated_at, :format => :short}
				li Metadata updated at: #{l @display.updated_at, :format => :short}
				li Created at: #{l @display.created_at, :format => :short}
	
	div.col-sm-6.col-md-4.col-lg-3
		= authorized_users @display
	div.col-sm-6.col-md-4.col-lg-3
		= tickets_partial @display

	div.col-md-6
		- if @display.override_queues.present?
			div.override_queue
				h2 Slides in override queue
				p 
					| The slides in override queue will be displayed as soon as possible interrupting the normal
					|  presentation flow.
				- @display.override_queues.each do |oq|
					= render oq.slide

app/views/displays/show.js.erb
$('#display_<%=@display.id.to_s%>').replaceWith('<%=j render @display %>');

app/views/displays/sortable_items.js.erb
$('[data-sortable]').html('<%=j render partial: 'sortable_overrides', locals: {overrides: @display.override_queues}%>');